<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Default
 * @package    Default_View
 * @subpackage Paginator
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: partial.phtml 103 2011-04-18 13:41:08Z sasquatch@bgscripts.com $
 */
?>

<?php

/**
 * Fix the params.
 */
if (empty($this->params)) {
    $this->params = array();
}

if ($this->pageCount > 1): ?>

<div class="common paginator">

<?php if (isset($this->previous)): ?>
    
    <a href="<?php echo $this->url(array_merge(array('page' => $this->previous), $this->params)); ?>" class="ui-corner-all">предишна</a>

<?php endif; ?>

<?php foreach ($this->pagesInRange as $page): ?>

  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array_merge(array('page' => $page), $this->params)); ?>" 
       class="ui-corner-all"><?php echo $page; ?></a>
  <?php else: ?>
	<a class="current ui-corner-all"><?php echo $page; ?></a>
  <?php endif; ?>

<?php endforeach; ?>

<?php if (isset($this->next)): ?>
	<a href="<?php echo $this->url(array_merge(array('page' => $this->next), $this->params)); ?>" class="ui-corner-all">следваща</a>

<?php endif; ?>

</div> <!-- end of .paginator -->

<?php endif; ?>