<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage Users
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: index.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php

    /**
     * Get users.
     */
    $users = $this->users;
    
    echo $this->stateInfo($this->translate('From here you can browse registered users'));
    
    /** Filter form. **/
    echo $this->form;
    
    ?>
    <table class="list">
        <tr>
            <td></td>
            <td><?php
                echo $this->translate('Username')
            ?></td>
            <td><?php
                echo $this->translate('ID')
            ?></td>
            <td><?php
                echo $this->translate('E-mail')
            ?></td>
            <td><?php
                echo $this->translate('Country')
            ?></td>
            <td><?php
                echo $this->translate('City')
            ?></td>
            <td><?php
                echo $this->translate('Access role')
            ?></td>
            <td></td>
        </tr>
    <?php
        /**
         * Display table rows.
         */
        echo $this->partialLoop('users/partial/list.phtml', $users);
    ?>
    </table>

<?php
    print $this->paginationControl($this->paginator, null, null, $this->params);
?>