<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage SEO
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: index.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>
<style type="text/css">
table, td, th
{
border:1px solid black;
}

</style>
<?php

	/** Display message **/
 //   	echo $this->message . "<br />";

//	echo "happy people";
?>
<h2 style="text-align: center;">РАЗПРЕДЕЛЕНИЕ НА УЧАСТНИЦИТЕ ПО ЗАЛИ</h2>
<br /><br /><br /><br />
<table style="width:100%;">
  <tr>
    <th>рег н</th>
    <th>Училище</th>
<th>Участник</th>
<th>Град</th>
<th>Клас</th>
<th>Ниво</th>
<th>Зала</th>
  </tr>
<?php
foreach ($this->approvedEntries as $row) {
			echo "<tr>\n<td>". $row->id . "</td>\n<td>" . $row->school .  "</td>\n<td>". $row->names . "</td>\n<td>" . $row->city . "</td>\n<td>" . $row->grade . "</td>\n<td>" . $row->level . "</td>\n<td>" . $row->room . "</td>\n</tr>\n";
}
?>
<!--
  <tr>
    <td>2</td>
    <td>ПМГ</td>
    <td>Име Презиме Фамилия</td>
    <td>Велико Търново</td>
    <td>12</td>
    <td>1</td>
    <td>306</td>
  </tr>
  

  <tr>
    <td>2</td>
    <td>ПМГ</td>
    <td>Име Презиме Фамилия</td>
    <td>Велико Търново</td>
    <td>11</td>
    <td>2</td>
    <td>506</td>
  </tr>


  <tr>
    <td>2</td>
    <td>ПМГ</td>
    <td>Име Презиме Фамилия</td>
    <td>Велико Търново</td>
    <td>12</td>
    <td>1</td>
    <td>202</td>
  </tr>

-->
</table>

<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
