<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage Localization
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: index.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php
    echo $this->stateInfo($this->translate("From here you can manage countries"));
    
    foreach ($this->countries as $countryValue)
    {
        $countryName = $countryValue['name'];
        $countryId = $countryValue['id'];
        $countryIcon = $countryValue['icon'];
        $domElementId = 'country' . $countryId;
        
        ?>
        <div id="<?php
            /**
             * country id for DOM element id.
             */
            echo $domElementId;
        ?>" class="ui-widget ui-state-highlight ui-corner-all recordBox">
            <div class="overflowHidden">
                <?php
                /**
                 * Get icon full path and url.
                 */
                $imagePath = $this->settings->l10n->iconsPath . $countryIcon;
                $imageUrl = $this->baseUrl('resources/common/icons/l10n/' . $countryIcon);
                /**
                 * Check icon existing
                 */                        
                $isIconValid = Zend_Validate::is($imagePath, 'File_IsImage');
                if ($isIconValid) {
                    echo '<img src="' . $imageUrl . '" ' 
                            . 'style="float: left; width: 16px; height: 16px"' 
                            . ' />';
                }
                    
                ?>
                <b class="ui-state-highlight languageTitle">
                    <?php 
                        echo $countryName;
                    ?>
                </b>
                
                <div class="floatRight">
                
                    <a class="iconButton pencil small" 
                       href="<?=$this->url(array('controller' => 'countries', 
                                                 'action' => 'edit', 
                                                 'id' => $countryId), 'tulipa', true)?>"></a>
                    <?php
                        $jQueryOptions = array(
                            'url' => $this->url(array(
                                'controller' => 'countries',
                                'action' => 'delete',
                                'id' => $countryId
                            ), 'tulipa', true),
                            'confirmMessage' => $this->translate('Are you sure you want to delete this country?'),
                            'elementToHide' => $domElementId
                        );
                    ?>
                    <a class="iconButton trash small delete" 
                       href="<?php
                            echo $jQueryOptions['url'];
                       ?>"
                       onclick="recordRemover.remove(<?php 
                            echo $this->escape(Zend_Json::encode($jQueryOptions));
                       ?>);return false;"></a>
                       
                </div>
                
            </div>
        </div>
    
    <?php
    }
    
    /**
     * Zend_Paginator partial.
     */
    echo $this->paginationControl($this->paginator);
?>