<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage Localization
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: index.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php
    echo $this->stateInfo($this->translate("From here you can manage cities in the site"));
    
    /**
     * Display filter form.
     */
    echo $this->form;
    
    if (!count($this->cities)) {
        echo $this->stateError($this->translate("No cities found"));
        return;
    }
?>
    <table class="list">
        <tr>
            <td></td>
            <td class="title"><?php
                echo $this->translate('City')
            ?></td>
            <td><?php
                echo $this->translate('Country')
            ?></td>
            <td class="short"></td>
        </tr>
<?php
    foreach ($this->cities as $cityValue)
    {
        $cityName = $cityValue['name'];
        $countryName = $cityValue['countryName'];
        $countryIcon = $cityValue['countryIcon'];
        $cityId = $cityValue['id'];
        $domElementId = 'city' . $cityId;
        
        ?>
        <tr id="<?php
            /**
             * City id for DOM element id.
             */
            echo $domElementId;
        ?>">
        <td></td>
        <td><?php
            echo $this->escape($cityName);
        ?></td>
        <td>
        <?php
            /**
             * Get icon full path and url.
             */
            $imagePath = $this->settings->l10n->iconsPath . $countryIcon;
            $imageUrl = $this->baseUrl('resources/common/icons/l10n/' . $countryIcon);
            /**
             * Check icon existing
             */                        
            $isIconValid = Zend_Validate::is($imagePath, 'File_IsImage');
            if ($isIconValid) {
                echo '<img src="' . $imageUrl . '" ' 
                        . 'style="float: left; width: 16px; height: 16px"' 
                        . ' />';
            }
                
            echo $this->escape($countryName);
        ?>
        </td>
        <td>
            <a class="iconButton pencil small" 
               href="<?=$this->url(array('controller' => 'cities', 
                                         'action' => 'edit', 
                                         'id' => $cityId), 'tulipa', true)?>"></a>
            <?php
                $jQueryOptions = array(
                    'url' => $this->url(array(
                        'controller' => 'cities',
                        'action' => 'delete',
                        'id' => $cityId
                    ), 'tulipa', true),
                    'confirmMessage' => $this->translate('Are you sure you want to delete this city?'),
                    'elementToHide' => $domElementId
                );
            ?>
            <a class="iconButton trash small delete" 
               href="<?php
                    echo $jQueryOptions['url'];
               ?>"
               onclick="recordRemover.remove(<?php 
                    echo $this->escape(Zend_Json::encode($jQueryOptions));
               ?>);return false;"></a>
        </td>
        </tr>
    
<?php
    }
?>
    </table>
<?php
    /**
     * Zend_Paginator partial.
     */
    echo $this->paginationControl($this->paginator, null, null, $this->params);
?>