<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage CRUD
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: edit.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php    
    
    /** Display CRUD module navigation **/
    echo $this->render('crud/partial/navigation.phtml');

    $this->placeholder('crudModuleName')->set($this->crudModuleName);    
    
    /**
     * Display CKEditor JavaScript.
     */
    echo $this->partial('crud/partial/scripts.phtml');
        
    if (isset($this->crudTranslator)) {
        $translate = $this->crudTranslator;
    } else {
        $translate = $this;
    }
    
    if (isset($this->descriptions->edit)) {
        echo $this->stateInfo($translate->translate($this->descriptions->edit));
    }
    
    /**
     * Display form.
     */
    echo $this->form;
    
    if (!empty($this->pictures)) {
        $this->placeholder('picturesModel')->set($this->picturesModel);        
        echo $this->fieldset('pictures', $this->partialLoop(
        	'crud/edit/picture.phtml', $this->pictures
        ));
    }