<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage CRUD
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: files.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php
    
    /** Display CRUD module navigation **/
    echo $this->render('crud/partial/navigation.phtml');
    
    $primaryKeyColumn = $this->filesModel->getPrimaryKeyColumn();
    $filenameColumn = $this->filesModel->getFilenameColumn();
    
    $this->placeholder('fields')->set(array($primaryKeyColumn,
                                            $filenameColumn));
    $this->placeholder('buttons')->set(array('delete' => true));
    $this->placeholder('crudModuleName')->set($this->crudModuleName);
    
    if (isset($this->crudTranslator)) {
        $translate = $this->crudTranslator;
    } else {
        $translate = $this;
    }
        
    if (empty($this->items)) {
        echo $this->stateError($this->translate('No items found'));
        return;
    }
    
    if (isset($this->descriptions->files)) {
        echo $this->stateInfo($translate->translate($this->descriptions->files));
    }
    
    ?>
    <table class="list">
        <tr>
        	<td></td>
            <td class="crud-row-id">
			<?php echo $this->translate('ID'); ?>
            </td>
            <td>
			<?php echo $this->translate('File'); ?>
            </td>
            <td class="list-options"></td>
        </tr>
        <?php foreach ($this->items as $item) : ?>
        <?php 
            $domElementId = $this->crudModuleName . '-row-' . $item['id'];
        ?>
        <tr id="<?php echo $domElementId; ?>">
			<td></td>
            <td><?php echo $this->escape($item[$primaryKeyColumn]); ?></td>
            <td>
            	<a class="link noJs" 
            	   href="<?php echo $this->baseUrl($this->filesModel->getUrl() . '/' . $item[$filenameColumn]); ?>"
            	   onclick="window.open(this.href);return false;">
                <?php echo $this->escape($item[$filenameColumn]); ?>
                </a>
            </td>
            <td>
            <?php
            $deleteUrl = $this->url(array(
                'action' => 'delete-file',
                'id' => $item['id']), 'crud'
            );
        
            $jQueryOptions = array(
                'url' => $deleteUrl,
                'confirmMessage' => $this->translate('Are you sure you want to delete this file?'),
                'elementToHide' => $domElementId
            );
        ?>
            <a class="iconButton trash small delete" 
            href="<?php
                echo $jQueryOptions['url'];
            ?>"
            onclick="recordRemover.remove(<?php 
                echo $this->escape(Zend_Json::encode($jQueryOptions));
            ?>);return false;"></a>
            </td>
        </tr>
        <?php endforeach;?>
    </table>
    
<?php
    print $this->paginationControl($this->paginator, null, null, $this->params);
?>