<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage CRUD
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: index.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php
    
    /** Display CRUD module navigation **/
    echo $this->render('crud/partial/navigation.phtml');

    $this->placeholder('fields')->set($this->browseFields);
    $this->placeholder('buttons')->set($this->buttons);
    $this->placeholder('crudModuleName')->set($this->crudModuleName);
    
    if (isset($this->crudTranslator)) {
        $translate = $this->crudTranslator;
    } else {
        $translate = $this;
    }
    
    if (isset($this->descriptions->index)) {
        echo $this->stateInfo($translate->translate($this->descriptions->index));
    }
    
    if (isset($this->filterForm)) {
        echo $this->filterForm;
    }
        
    if (empty($this->items)) {
        echo $this->stateError($this->translate('No items found'));
        return;
    }
    
    ?>
    <table class="list">
        <tr>
        	<td></td>
        	<?php foreach ($this->browseFields as $key => $field) : ?>
            <td<?php if($field == 'id') echo ' class="crud-row-id"'; ?>>
            <?php
                if (isset($this->crudConfig->form->default->elements->$field->options->label)) {
                    $columnTitle = $this->crudConfig->form->default->elements->$field->options->label;
                } else if (isset($this->crudConfig->form->lang->elements->$field->options->label)) {
                    $columnTitle = $this->crudConfig->form->lang->elements->$field->options->label;
                } else {
                    $columnTitle = $translate->translate(ucfirst($field));
                }
                echo $this->escape($columnTitle); 
            ?>
            </td>
            <?php endforeach; ?>
            <?php if ($this->buttons->delete || $this->buttons->edit) : ?>
            <td class="list-options"></td>
            <?php endif;?>
        </tr>
    	<?php 
    	    echo $this->partialLoop('crud/partial/item.phtml', $this->items);
    	?>
    </table>
    
<?php
    print $this->paginationControl($this->paginator, null, null, $this->params);
?>