<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_Layout
 * @subpackage Scripts
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: center.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>
<div class="center login">
    
    <?php
        /**
         * Create the page content. Concat with status messages (if any)
         */
        $pageContent = $this->status($this->statusMessages) . $this->layout()->content;
        
        $activePage = $this->navigation()->findActive($this->mixedNavigation, -1);
        
        /**
         * Center content bar.
         */
        echo $this->bar($this->translate($activePage['page']), $pageContent, 'lock', 'content', false);
        
    ?>

</div>