<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Default
 * @package    Default_View
 * @subpackage Articles
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: partial.phtml 103 2011-04-18 13:41:08Z sasquatch@bgscripts.com $
 */
?>

<?php if (isset($this->topArticles) && $this->topArticles->count() >= 4) : ?>
<div class="common last-news">
	    	
	<?php 
	$this->topArticles = $this->topArticles->toArray();
	$mainArticle = $this->topArticles[0];
	echo $this->article($mainArticle, true);
	?>
    
    <div class="common other">
    	<?php 
    	    foreach($this->topArticles as $article) : 
    	        echo $this->article($article, false, true);
    	    endforeach;
	    ?>
    </div> <!-- end of .last-other -->
    
    
</div> <!-- end of .last-news -->

<hr />

<?php endif; ?>