<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_Layout
 * @subpackage Scripts
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: bar.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>
<div class="bar"<?php
    /**
     * Add JavaScript DOM Id if is set
     */
    if (!empty($this->domId)) {
        ?>
         id="<?=$this->domId?>"
        <?php
    }
    
?>>
    
    <div class="top ui-corner-top">
    
        <img src="<?=$this->baseUrl('resources/tulipa/icons/24x24/' . $this->icon . '.png')?>" alt="" />
        
        <a href="JavaScript:void(0)">
            <?php
                echo $this->translate(trim($this->title)); 
            ?>
        </a>
        
        <?php
            //var_dump($this->getHelper('translate')->getTranslator()->getMessages());
            if ($this->closeButton) {
        ?>
        
        <span class="arrow down"></span>

        <span class="sep"></span>
        
        <?php
            }
        ?>
        
    </div>
    
    <div class="content ui-corner-bottom">
        <?=$this->content?>
    </div>
    
</div>