<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_Layout
 * @subpackage Scripts
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: left.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>
<div class="left">
    
    <?php
    
    $mainAcl = Zend_Registry::get('Zend_Acl');
    
    $mainNav = $this->navigation()
                    ->setAcl($mainAcl)
                    ->menu($this->navigation['main'])
                    ->setMinDepth(1)
                    ->render();

    if (!empty($mainNav)) {
        echo $this->bar($this->translate('Main menu'), $mainNav, 'pin');
    }
    
    $accessNav = $this->navigation()
                      ->setAcl($mainAcl)
                      ->menu($this->navigation['rules'])
                      ->setMinDepth(1)
                      ->render();
    
    
    if (!empty($accessNav)) {
        echo $this->bar($this->translate('Access'), $accessNav, 'lock');
    }
    
    $otherNav = $this->navigation()
                     ->setAcl($mainAcl)
                     ->menu($this->navigation['other'])
                     ->setMinDepth(1)
                     ->render();
                     
    if (!empty($otherNav)) {
        echo $this->bar($this->translate('Other'), $otherNav, 'lock');
    }
        
    $localeNav = $this->navigation()
                      ->setAcl($mainAcl)
                      ->menu($this->navigation['l10n'])
                      ->setMinDepth(1)
                      ->render();
    
    if (!empty($localeNav)) {
        echo $this->bar($this->translate('L10n/I18n'), $localeNav);
    }
    
    $crudNav = $this->navigation()
                    ->setAcl($mainAcl)
                    ->menu($this->navigation['crudModules'])
                    ->setMinDepth(1)
                    ->render();
                    
    if (!empty($crudNav)) {
        echo $this->bar($this->translate('CRUD modules'), $crudNav, 'tools');
    }
    ?>
	
</div>