<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_Layout
 * @subpackage Scripts
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: navigation.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>
<div class="navigation" id="breadcrumbs">
    <div>
            
        <a href="<?=$this->url(array('module' => 'tulipa', 'controller' => 'index', 'action' => 'index'), 'default', true)?>">
            <img src="<?=$this->baseUrl('resources/tulipa/icons/24x24/home.png')?>" 
                 alt="home" />
        </a>
        
        <?php
            
            if (!empty($this->newParams)) {
                $front = Zend_Controller_Front::getInstance();
                $front->getRequest()
                      ->setParams($this->newParams);
            }
            
            $container = new Zend_Navigation($this->mixedNavigationArray);
                        
            echo $this->navigation()                           
                       ->breadcrumbs($container)
                       ->setMinDepth(-1)
                       ->setLinkLast(true)
                       ->setSeparator('<img src=" ' . $this->baseUrl('resources/tulipa/icons/24x24/next.png') 
                                                    . ' " alt="next" />');
        ?>
    </div>
</div>