<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage Paginator
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: partial.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php

/**
 * Fix the params.
 */
if (empty($this->params)) {
    $this->params = array();
}

if ($this->pageCount > 1): ?>

<div class="paginator">

<?php if (isset($this->previous)): ?>

  <a class="page" href="<?php echo $this->url(array_merge(array('page' => $this->previous), $this->params)); ?>">

    <span class="left"></span>

  </a>

<?php endif; ?>

<?php foreach ($this->pagesInRange as $page): ?>

  <?php if ($page != $this->current): ?>

    <a class="page" href="<?php echo $this->url(array_merge(array('page' => $page), $this->params)); ?>">

        <?php echo $page; ?>

    </a>

  <?php else: ?>

    <a class="page current"><?php echo $page; ?></a>

  <?php endif; ?>

<?php endforeach; ?>

<?php if (isset($this->next)): ?>

  <a class="page" href="<?php echo $this->url(array_merge(array('page' => $this->next), $this->params)); ?>">

    <span class="right"></span>

  </a>

<?php endif; ?>

</div>

<?php endif; ?>