<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage Roles
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: index.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php
    /**
     * Get Acl Roles.
     */
    $roles = $this->roles;
    
    echo $this->stateInfo($this->translate('From here you can browse the roles that are available'));
    
    ?>
    <table class="list">
        <tr>
            <td></td>
            <td class="title"><?php
                echo $this->translate('Name')
            ?></td>
            <td><?php
                echo $this->translate('Code')
            ?></td>
            <td><?php
                echo $this->translate('Parent')
            ?></td>
            <td></td>
        </tr>
    <?php
    foreach ($roles as $role)
    {
        $id = $role['id'];
        $domElementId = 'role' . $id;
        $name = $role['name'];
        $parentName = $role['parentName'] ? $role['parentName'] : $this->translate('None');
        $title = $role['translations'];
        if (!empty($role['translations'])) {
            /**
             * Configure translations.
             */
            $allTranslations = explode(',', $role['translations']);
            foreach ($allTranslations as $translation) {
                $pieces = explode(' - ', $translation);
                if ($pieces[0] == Application_Model_Language::getSessionLang()->id) {
                    $title = $pieces[1];
                    break;
                }
            }
        }
        
        ?>
        <tr id="<?php
            echo $domElementId;
        ?>">
            <td></td>
            <td><?php
                echo $this->escape($title);
            ?></td>
            <td><?php
                echo $this->escape($name);
            ?></td>
            <td><?php
                echo $this->escape($parentName);
            ?></td>
            <td><a class="iconButton pencil small" 
                   href="<?=$this->url(array('controller' => 'roles', 
                                             'action' => 'edit', 
                                             'id' => $id), 'tulipa', true)?>"></a><?php
                    $jQueryOptions = array(
                        'url' => $this->url(array(
                            'controller' => 'roles',
                            'action' => 'delete',
                            'id' => $id
                        ), 'tulipa', true),
                        'confirmMessage' => $this->translate('Are you sure you want to delete this role?'),
                        'elementToHide' => $domElementId
                    );
                ?><a class="iconButton trash small delete" 
                   href="<?php
                        echo $jQueryOptions['url'];
                   ?>"
                   onclick="recordRemover.remove(<?php 
                        echo $this->escape(Zend_Json::encode($jQueryOptions));
                   ?>);return false;"></a></td>
        </tr>
        <?php
    
        
    }
    ?>
    </table>
    <?php
    
    echo $this->stateInfo($this->translate('The "Parent" column shows from which role the particular role inherits privileges'));

?>
