<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Application
 * @package    Application_Models
 * @subpackage Language
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: Converter.php 103 2011-04-18 13:41:08Z sasquatch@bgscripts.com $
 */

/**
 * Converter - *.mo to php array.
 * 
 * @category   Application
 * @package    Application_Models
 * @subpackage Language
 * @copyright  Copyright (c) 2010 Sasquatch MC
 */
class Application_Model_Language_Converter
{
    /**
     * Convert .mo file to php array.
     * 
     * @param string $file
     * @return string PHP array exported string
     */
	static public function convert($file)
    {
        $translate = new Zend_Translate('gettext', $file);
        $translations = $translate->getAdapter()->getMessages();
        
        $phpCode = self::createPhp($translations);
        
        return $phpCode;
    }
    
    /**
     * Create php code.
     * 
     * @param array $array
     * @return string PHP array exported string
     */
	static public function createPhp($array)
    {
        $code = var_export($array, true);
        $phpCodeBody = 'return ' . $code . ';';
                
        $file = new Zend_CodeGenerator_Php_File(array(
          'docblock' => new Zend_CodeGenerator_Php_Docblock(array(
              'shortDescription' => 'Tulipa © Core ' . "\n"
                                    . 'Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>' . "\n"
                                    . '                     http://bgscripts.com',
              'longDescription' =>  'LICENSE' . "\n\n"
                                    . 'A copy of this license is bundled with this package in the file LICENSE.txt.' . "\n\n"
                                    . 'Platform that uses this site is protected by copyright.' . "\n"
                                    . 'It is provided solely for the use of this site and all its copying,' . "\n"
                                    . 'processing or use of parts thereof is prohibited and pursued by law.' . "\n\n"
                                    . 'This is language definition file generated by Zend_CodeGenerator and it`s for use of '
                                    . 'Tulipa © Web Administration System.',
              'tags'             => array(
                  array(
                      'name'        => 'category',
                      'description' => 'Application',
                  ),
                  array(
                      'name'        => 'package',
                      'description' => 'Application_Languages'
                  ),
                  array(
                      'name'        => 'copyright',
                      'description' => 'Copyright (c) 2010 Sasquatch MC'
                  ),
                  array(
                      'name'        => 'version',
                      'description' => '$Id: Converter.php 103 2011-04-18 13:41:08Z sasquatch@bgscripts.com $'
                  )
              ),
          )),
          'body'     => $phpCodeBody,
        ));
        
        return $file->generate();
    }
}