<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage Language
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: index.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php
    echo $this->stateInfo($this->translate("From here you can manage system languages"));
    
    foreach ($this->languages as $languageValue)
    {
        $languageName = $languageValue['name'];
        $languageTitle = $languageValue['title'];
        $languageId = $languageValue['id'];
        $languageIcon = $languageValue['icon'];
        $domElementId = 'language' . $languageId;
        
        ?>
        <div id="<?php
            /**
             * Language id for DOM element id.
             */
            echo $domElementId;
        ?>" class="ui-widget ui-state-highlight ui-corner-all recordBox">
            <div class="overflowHidden">
                <?php
                /**
                 * Get icon full path and url.
                 */
                $imagePath = $this->settings->langs->iconsPath . $languageIcon;
                $imageUrl = $this->baseUrl('resources/common/icons/langs/' . $languageIcon);
                /**
                 * Check icon existing
                 */                        
                $isIconValid = Zend_Validate::is($imagePath, 'File_IsImage');
                if ($isIconValid) {                    
                    $icon = strtolower($languageName);
                    echo '<img src="' . $imageUrl . '" ' 
                            . 'style="float: left; width: 16px; height: 16px"' 
                            . ' />';
                }
                    
                ?>
                <b class="ui-state-highlight languageTitle">
                    <?php 
                        echo $languageTitle;
                    ?>
                </b>
                
                <div class="floatRight">
                
                    <a class="iconButton pencil small" 
                       href="<?=$this->url(array('controller' => 'langs', 
                                                 'action' => 'edit', 
                                                 'id' => $languageId), 'tulipa', true)?>"></a>
                    <?php
                        $jQueryOptions = array(
                            'url' => $this->url(array(
                                'controller' => 'langs',
                                'action' => 'delete',
                                'id' => $languageId
                            ), 'tulipa', true),
                            'confirmMessage' => $this->translate('Are you sure you want to delete this language?'),
                            'elementToHide' => $domElementId
                        );
                    ?>
                    <a class="iconButton trash small delete" 
                       href="<?php
                            echo $jQueryOptions['url'];
                       ?>"
                       onclick="recordRemover.remove(<?php 
                            echo $this->escape(Zend_Json::encode($jQueryOptions));
                       ?>);return false;"></a>
                       
                </div>
                
            </div>
        </div>
    
    <?php
    }
    
    /** Generates simple line breaks **/
    echo $this->lineBreaks(2);
        
    echo $this->stateAttention($this->translate("You can not delete the language that is set by default in application/configs/common.ini"));
    echo $this->stateAttention($this->translate("You can`t delete all the languages. At least one is required"));
?>