<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage CRUD
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: scripts.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<script type="text/javascript">
$(document).ready(function()
{
	$('.<?php echo Application_Form_Element_Keywords::CSS_CLASS ?>').textboxlist({bitsOptions:{editable:{addKeys: [188]}}});
	
	$.each(CKEDITOR.instances, function(key, value) {
		CKEDITOR.remove(CKEDITOR.instances[key]);
	});

    $('.<?php echo Application_Form_Element_Editor::CSS_CLASS ?>').ckeditor({
        height: 340
    });

    $.each(CKEDITOR.instances, function(key, value) {
    	CKFinder.setupCKEditor(value, '<?php             
	        echo $this->baseUrl('ckfinder');
	    ?>');
	});
        
    $('.date-picker').datepicker({
        changeMonth: true,
    	changeYear: true,
        altFormat: 'yy-mm-dd',
        dateFormat: 'yy-mm-dd',
        showAnim: 'fadeIn'
    });
});
</script>