<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage CRUD
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: sub-modules.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php
$crudModuleName = $this->placeholder('crudModuleName')->getValue();
$langName = Application_Model_Language::getSessionLang()->name;

if (isset($this->subModules)) :
?>
<div class="crud-sub-modules">
<?php
    foreach ($this->subModules as $moduleName => $moduleConfig) :
    
        $moduleTitle = isset($moduleConfig->name->default) ? $moduleConfig->name->default
                                                           : ucfirst($moduleName);
                                                           
        $moduleTitle = isset($moduleConfig->name->$langName) ? $moduleConfig->name->$langName
                                                             : $moduleTitle;
?>
	<a href="<?php 
	    echo $this->url(array(
	    	'crudModuleName' => $crudModuleName, 'subModule' => $moduleName
	    ), 'crudSub', true); 
	?>"><?php echo $this->escape($moduleTitle) ?></a>
<?php
    endforeach;
?>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('.crud-sub-modules').buttonset();
	});
</script>
<?php
endif;