<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage Users
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: list.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php
    $id = $this->id;
    $domElementId = 'user' . $id;
    /** Username **/
    $username = $this->username;
    /** E-mail **/
    $email = $this->email;
    /** Country **/
    $countryName = $this->countryName;
    /** City **/
    $cityName = $this->cityName;
    /** Date of registration **/
    $dateOfRegistration = $this->dateOfRegistration;
    /** ACL Role name **/
    $roleName = $this->roleName;
    
    ?>
    <tr id="<?php
        echo $domElementId;
    ?>">
        <td></td>
        <td><?php
            echo $this->escape($username);
        ?></td>
        <td><?php
            echo (int) $id;
        ?></td>
        <td><?php
            echo $this->escape($email);
        ?></td>
        <td><?php
            echo $this->escape($countryName);
        ?></td>
        <td class="users-city-name"><?php
            echo $this->escape($cityName);
        ?></td>
        <td><?php
            echo $this->escape($roleName);
        ?></td>
        <td><a class="iconButton pencil small" 
               href="<?=$this->url(array('controller' => 'users', 
                                         'action' => 'edit', 
                                         'id' => $id), 'tulipa', true)?>"></a><?php
                $jQueryOptions = array(
                    'url' => $this->url(array(
                        'controller' => 'users',
                        'action' => 'delete',
                        'id' => $id
                    ), 'tulipa', true),
                    'confirmMessage' => $this->translate('Are you sure you want to delete this user?'),
                    'elementToHide' => $domElementId
                );
            ?><a class="iconButton trash small delete" 
               href="<?php
                    echo $jQueryOptions['url'];
               ?>"
               onclick="recordRemover.remove(<?php 
                    echo $this->escape(Zend_Json::encode($jQueryOptions));
               ?>);return false;"></a></td>
    </tr>