<?php
/**
 * Tulipa © Core 
 * Copyright © 2010 Sasquatch <Joan-Alexander Grigorov>
 *                      http://bgscripts.com
 * 
 * LICENSE
 * 
 * A copy of this license is bundled with this package in the file LICENSE.txt.
 * 
 * Copyright © Tulipa
 * 
 * Platform that uses this site is protected by copyright. 
 * It is provided solely for the use of this site and all its copying, 
 * processing or use of parts thereof is prohibited and pursued by law.
 * 
 * All rights reserved. Contact: office@bgscripts.com
 * 
 * Платформата, която използва този сайт е със запазени авторски права. 
 * Тя е предоставена само за ползване от конкретния сайт и всяко нейно копиране, 
 * преработка или използване на части от нея е забранено и се преследва от закона. 
 * 
 * Всички права запазени. За контакти: office@bgscripts.com
 *
 * @category   Tulipa
 * @package    Tulipa_View
 * @subpackage Index
 * @copyright  Copyright (c) 2010 Sasquatch MC
 * @version    $Id: notification.phtml 185 2011-09-22 14:49:32Z sasquatch@bgscripts.com $
 */
?>

<?php 
    $domElementId = 'notification-' . $this->id;
?>

<div class="notification" id="<?php echo $domElementId; ?>">
<?php
    $title = $this->title;
    $content = $this->content;
    $jQueryOptions = array(
        'url' => $this->url(array(
            'controller' => 'notifications',
            'action' => 'delete',
            'id' => $this->id
        ), 'tulipa', true),
        'confirmMessage' => $this->translate('Are you sure you want to delete this message?'),
        'elementToHide' => $domElementId
    );
    $button = $this->anchor('', 'iconButton trash small delete', $jQueryOptions['url'], null, 'a', 'recordRemover.remove(' .  
                    $this->escape(Zend_Json::encode($jQueryOptions)) . ');return false;');
    echo $this->stateInfo(sprintf('<h3>%s</h3><br /><i>%s</i><br /><br />%s', $title, $content, $button));
    echo $this->lineBreaks(2);
?>
</div>